/**
 * `cert-preview` — X.509 certificate and key inspection, compiled to WebAssembly.
 *
 * The same core library powers the CLI and the browser/Node front ends, so
 * output is identical across platforms. Typical usage:
 *
 * ```ts
 * import { load } from "cert-preview";
 *
 * const view = await load();
 * const report = view.inspect(new TextEncoder().encode(pemString));
 * console.log(report.bundle.items.length);
 * ```
 *
 * In Node, prefer `import { load } from "cert-preview/node"`; in a bundler
 * targeting the browser, `cert-preview/browser` (also the default `load`).
 */

// Public types mirrored 1:1 from the Rust model (generated by ts-rs).
export type { AccessDescription } from "./generated/AccessDescription";
export type { AlgorithmInfo } from "./generated/AlgorithmInfo";
export type { BasicConstraintsInfo } from "./generated/BasicConstraintsInfo";
export type { Bundle } from "./generated/Bundle";
export type { BundleItem } from "./generated/BundleItem";
export type { CertificateInfo } from "./generated/CertificateInfo";
export type { CertificateStatus } from "./generated/CertificateStatus";
export type { ChainSummary } from "./generated/ChainSummary";
export type { Diagnostic } from "./generated/Diagnostic";
export type { DistinguishedName } from "./generated/DistinguishedName";
export type { ErrorCode } from "./generated/ErrorCode";
export type { ErrorPayload } from "./generated/ErrorPayload";
export type { Extensions } from "./generated/Extensions";
export type { Fingerprints } from "./generated/Fingerprints";
export type { GeneralNameInfo } from "./generated/GeneralNameInfo";
export type { HostnameMatch } from "./generated/HostnameMatch";
export type { PrivateKeyFormat } from "./generated/PrivateKeyFormat";
export type { PrivateKeyInfo } from "./generated/PrivateKeyInfo";
export type { PublicKeyInfo } from "./generated/PublicKeyInfo";
export type { RawExtension } from "./generated/RawExtension";
export type { RdnAttribute } from "./generated/RdnAttribute";
export type { Report } from "./generated/Report";
export type { Severity } from "./generated/Severity";
export type { UnsupportedItem } from "./generated/UnsupportedItem";
export type { Validity } from "./generated/Validity";
export type { ValidityState } from "./generated/ValidityState";
export type { ValidityStatus } from "./generated/ValidityStatus";

// Error handling and the call-surface types.
export { CertViewError, asCertViewError } from "./errors";
export type { CertViewApi, InspectOptions } from "./types";

// Default entry point (browser build). Node consumers should import
// `cert-preview/node` instead to avoid a browser-only wasm loader.
export { load } from "./loader-browser";
